"""Common Pydantic models used across the SDK."""

from typing import Optional, List, Literal
from pydantic import BaseModel, Field


# Task statuses
TaskStatus = Literal["submitted", "processing", "succeed", "failed"]

# Model versions
ModelName = Literal[
    "kling-v1",
    "kling-v1-5",
    "kling-v1-6",
    "kling-v2-master",
    "kling-v2-1",
    "kling-v2-1-master",
    "kling-v2-5-turbo",
]

# Video modes
VideoMode = Literal["std", "pro"]

# Aspect ratios
AspectRatio = Literal["16:9", "9:16", "1:1"]

# Duration
VideoDuration = Literal["5", "10"]


class VideoResult(BaseModel):
    """Video result model."""

    id: str = Field(..., description="Generated video ID; globally unique")
    url: str = Field(..., description="URL for the generated video")
    duration: str = Field(..., description="Total video duration in seconds")


class AudioResult(BaseModel):
    """Audio result model."""

    id: str = Field(..., description="Generated audio ID; globally unique")
    url_mp3: Optional[str] = Field(None, description="URL for audio in MP3 format")
    url_wav: Optional[str] = Field(None, description="URL for audio in WAV format")
    url: Optional[str] = Field(None, description="URL for audio (generic)")
    duration_mp3: Optional[str] = Field(None, description="Duration in MP3 format")
    duration_wav: Optional[str] = Field(None, description="Duration in WAV format")
    duration: Optional[str] = Field(None, description="Duration (generic)")


class TaskInfo(BaseModel):
    """Task info model."""

    external_task_id: Optional[str] = Field(None, description="Customer-defined task ID")


class TaskResult(BaseModel):
    """Task result model."""

    videos: Optional[List[VideoResult]] = Field(None, description="Generated videos")
    audios: Optional[List[AudioResult]] = Field(None, description="Generated audios")


class TaskResponse(BaseModel):
    """Generic task response model."""

    task_id: str = Field(..., description="Task ID generated by the system")
    task_status: TaskStatus = Field(..., description="Task status")
    task_status_msg: Optional[str] = Field(
        None, description="Task status message (e.g., failure reason)"
    )
    task_info: Optional[TaskInfo] = Field(None, description="Task creation parameters")
    task_result: Optional[TaskResult] = Field(None, description="Task results")
    created_at: int = Field(..., description="Task creation time (Unix timestamp in ms)")
    updated_at: int = Field(..., description="Task update time (Unix timestamp in ms)")


class APIResponse(BaseModel):
    """Generic API response wrapper."""

    code: int = Field(..., description="Error code")
    message: str = Field(..., description="Error message")
    request_id: str = Field(..., description="Request ID generated by the system")
    data: Optional[TaskResponse] = Field(None, description="Response data")


class CameraConfig(BaseModel):
    """Camera configuration for camera control."""

    horizontal: Optional[float] = Field(
        None,
        ge=-10,
        le=10,
        description="Horizontal movement (translation along x-axis)",
    )
    vertical: Optional[float] = Field(
        None,
        ge=-10,
        le=10,
        description="Vertical movement (translation along y-axis)",
    )
    pan: Optional[float] = Field(
        None,
        ge=-10,
        le=10,
        description="Pan (rotation around x-axis)",
    )
    tilt: Optional[float] = Field(
        None,
        ge=-10,
        le=10,
        description="Tilt (rotation around y-axis)",
    )
    roll: Optional[float] = Field(
        None,
        ge=-10,
        le=10,
        description="Roll (rotation around z-axis)",
    )
    zoom: Optional[float] = Field(
        None,
        ge=-10,
        le=10,
        description="Zoom (focal length change)",
    )


class CameraControl(BaseModel):
    """Camera control parameters."""

    type: Literal["simple", "down_back", "forward_up", "right_turn_forward", "left_turn_forward"] = (
        Field(..., description="Predefined camera movement type")
    )
    config: Optional[CameraConfig] = Field(
        None, description="Camera configuration (required for 'simple' type)"
    )
